name: Run integrations tests

on: [workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn install
      - name: Test project (develop environment)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: yarn cy:run:dev
        env:
          CYPRESS_BASE_URL: ${{secrets.CYPRESS_BASE_URL_DEV}}
      - name: Test project (stage environment)
        if: ${{ github.ref == 'refs/heads/stage' }}
        run: yarn cy:run
        env:
          CYPRESS_BASE_URL: ${{secrets.CYPRESS_BASE_URL_STAGE}}
      - name: Test project (prod environment)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: yarn cy:run
        env:
          CYPRESS_BASE_URL: ${{secrets.CYPRESS_BASE_URL}}
